import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {ModeToggle} from '@/components/ModeToggle';
import {Button} from '@/components/ui/button';
import {LogIn, LogOut} from "lucide-react";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          {/* Header */}
          <header className="sticky top-0 z-50 bg-primary text-primary-foreground p-4 flex items-center justify-between">
            <div className="flex items-center">
              {/* Dummy Logo - Replace with your actual logo */}
              <svg
                width="30"
                height="30"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="mr-2"
              >
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                <line x1="9" y1="3" x2="9" y2="21" />
              </svg>
              TABLET-TEACHING
            </div>
            <ModeToggle />
          </header>

          {/* Main Content */}
          <main className="flex-1">{children}</main>

          {/* Footer */}
          <footer className="sticky bottom-0 z-50 bg-primary text-primary-foreground p-4 flex items-center justify-between">
            <div>&copy; {new Date().getFullYear()} Tablet Lehre</div>
            <div>Wichtige Infos</div>
            <Button variant="secondary">
              <LogIn className="mr-2 h-4 w-4" />
              Anmelden
            </Button>
          </footer>
        </div>
      </body>
    </html>
  );
}




